[zsh]
'files/.zshrc' = '~/.zshrc'

[tmux]
'files/.tmux.conf' = '~/.tmux.conf'

[vim]
'files/.vimrc' = '~/.vimrc'

[vscode]
'files/vscode-user-settings.json' = '~/.config/Code/User/settings.json'

[starship]
'files/starship.toml' = '~/.config/starship.toml'

[alacritty]
'files/alacritty.toml' = '~/.config/alacritty/alacritty.toml'

[helix]
'files/helix.toml' =  '~/.config/helix/config.toml'

[zellij]
'files/zellij.kdl' =  '~/.config/zellij/config.kdl'
