[font]
size = 14.0

[font.normal]
family = "Inconsolata"

[terminal.shell]
# args = ["-c", "tmux", "new-session"]
# args = ["-c", "zellij"]
program = "/bin/zsh"

[window]
decorations = "full"
startup_mode = "Maximized"
opacity = 0.95

[terminal]

