[font]
size = 14.0

[font.normal]
family = "Inconsolata"

[shell]
# args = ["-c", "tmux", "new-session"]
args = ["-c", "zellij"]
program = "/bin/zsh"

[window]
decorations = "none"
# startup_mode = "Maximized"
