add_newline = false

format = """\
  $time\
  $directory\
  $git_branch\
  $git_status\
  $cmd_duration\
  $character\
  """

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%R"

[git_status]
format = '([\[$deleted$renamed$modified$untracked\]]($style) )'

[cmd_duration]
format = '[$duration]($style) '
